// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.AlchemyDataNewsAPI
{

    internal class AlchemyDataNewsAPIMainClass
    {

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("usage")]
        public string Usage { get; set; }

        [JsonProperty("totalTransactions")]
        public string TotalTransactions { get; set; }

        [JsonProperty("result")]
        public Result Result { get; set; }
    }

}
