// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.AlchemyDataNewsAPI
{

    internal class Concept
    {

        [JsonProperty("knowledgeGraph")]
        public KnowledgeGraph KnowledgeGraph { get; set; }

        [JsonProperty("relevance")]
        public double Relevance { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }
    }

}
