// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.AlchemyDataNewsAPI
{

    internal class Doc
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("source")]
        public Source Source { get; set; }

        [JsonProperty("timestamp")]
        public int Timestamp { get; set; }
    }

}
