// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.AlchemyDataNewsAPI
{

    internal class Enriched
    {

        [JsonProperty("url")]
        public Url Url { get; set; }
    }

}
