// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.TwitterApiClasses
{

    internal class Author
    {

        [JsonProperty("gender")]
        public string Gender { get; set; }

        [JsonProperty("parenthood")]
        public Parenthood Parenthood { get; set; }

        [JsonProperty("location")]
        public Location Location { get; set; }

        [JsonProperty("maritalStatus")]
        public MaritalStatus MaritalStatus { get; set; }
    }

}
