// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.TwitterApiClasses
{

    internal class Cde
    {

        [JsonProperty("author")]
        public Author Author { get; set; }

        [JsonProperty("content")]
        public Content Content { get; set; }
    }

}
