// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.TwitterApiClasses
{

    internal class Evidence
    {

        [JsonProperty("polarity")]
        public string Polarity { get; set; }

        [JsonProperty("sentimentTerm")]
        public string SentimentTerm { get; set; }
    }

}
