// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.TwitterApiClasses
{

    internal class Gnip
    {

        [JsonProperty("language")]
        public Language Language { get; set; }

        [JsonProperty("urls")]
        public Url2[] Urls { get; set; }

        [JsonProperty("profileLocations")]
        public ProfileLocation[] ProfileLocations { get; set; }
    }

}
