// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.TwitterApiClasses
{

    internal class MaritalStatus
    {

        [JsonProperty("isMarried")]
        public string IsMarried { get; set; }

        [JsonProperty("evidence")]
        public string Evidence { get; set; }
    }

}
