// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.TwitterApiClasses
{

    internal class Message
    {

        [JsonProperty("postedTime")]
        public string PostedTime { get; set; }

        [JsonProperty("verb")]
        public string Verb { get; set; }

        [JsonProperty("link")]
        public string Link { get; set; }

        [JsonProperty("inReplyTo")]
        public InReplyTo InReplyTo { get; set; }

        [JsonProperty("generator")]
        public Generator Generator { get; set; }

        [JsonProperty("body")]
        public string Body { get; set; }

        [JsonProperty("favoritesCount")]
        public int FavoritesCount { get; set; }

        [JsonProperty("objectType")]
        public string ObjectType { get; set; }

        [JsonProperty("actor")]
        public Actor Actor { get; set; }

        [JsonProperty("provider")]
        public Provider Provider { get; set; }

        [JsonProperty("twitter_filter_level")]
        public string TwitterFilterLevel { get; set; }

        [JsonProperty("twitter_entities")]
        public TwitterEntities TwitterEntities { get; set; }

        [JsonProperty("twitter_lang")]
        public string TwitterLang { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("retweetCount")]
        public int RetweetCount { get; set; }

        [JsonProperty("gnip")]
        public Gnip Gnip { get; set; }

        [JsonProperty("object")]
        public Object Object { get; set; }

        [JsonProperty("twitter_quoted_status")]
        public TwitterQuotedStatus TwitterQuotedStatus { get; set; }
    }

}
