// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.TwitterApiClasses
{

    internal class Object3
    {

        [JsonProperty("summary")]
        public string Summary { get; set; }

        [JsonProperty("postedTime")]
        public string PostedTime { get; set; }

        [JsonProperty("link")]
        public string Link { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("objectType")]
        public string ObjectType { get; set; }
    }

}
