// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.TwitterApiClasses
{

    internal class Object1
    {

        [JsonProperty("summary")]
        public string Summary { get; set; }

        [JsonProperty("postedTime")]
        public string PostedTime { get; set; }

        [JsonProperty("link")]
        public string Link { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("objectType")]
        public string ObjectType { get; set; }

        [JsonProperty("verb")]
        public string Verb { get; set; }

        [JsonProperty("generator")]
        public Generator2 Generator { get; set; }

        [JsonProperty("body")]
        public string Body { get; set; }

        [JsonProperty("favoritesCount")]
        public int? FavoritesCount { get; set; }

        [JsonProperty("actor")]
        public Actor2 Actor { get; set; }

        [JsonProperty("provider")]
        public Provider2 Provider { get; set; }

        [JsonProperty("twitter_filter_level")]
        public string TwitterFilterLevel { get; set; }

        [JsonProperty("twitter_entities")]
        public TwitterEntities2 TwitterEntities { get; set; }

        [JsonProperty("twitter_lang")]
        public string TwitterLang { get; set; }

        [JsonProperty("retweetCount")]
        public int? RetweetCount { get; set; }

        [JsonProperty("object")]
        public Object2 Object { get; set; }
    }

}
