// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.TwitterApiClasses
{

    internal class Parenthood
    {

        [JsonProperty("isParent")]
        public string IsParent { get; set; }

        [JsonProperty("evidence")]
        public string Evidence { get; set; }
    }

}
