// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.TwitterApiClasses
{

    internal class ProfileLocation
    {

        [JsonProperty("geo")]
        public Geo Geo { get; set; }

        [JsonProperty("address")]
        public Address Address { get; set; }

        [JsonProperty("displayName")]
        public string DisplayName { get; set; }

        [JsonProperty("objectType")]
        public string ObjectType { get; set; }
    }

}
