// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.TwitterApiClasses
{

    internal class Tweet
    {

        [JsonProperty("cde")]
        public Cde Cde { get; set; }

        [JsonProperty("message")]
        public Message Message { get; set; }

        [JsonProperty("cdeInternal")]
        public CdeInternal CdeInternal { get; set; }
    }

}
