// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.TwitterApiClasses
{

    internal class TwitterQuotedStatus
    {

        [JsonProperty("postedTime")]
        public string PostedTime { get; set; }

        [JsonProperty("verb")]
        public string Verb { get; set; }

        [JsonProperty("link")]
        public string Link { get; set; }

        [JsonProperty("inReplyTo")]
        public InReplyTo2 InReplyTo { get; set; }

        [JsonProperty("generator")]
        public Generator3 Generator { get; set; }

        [JsonProperty("body")]
        public string Body { get; set; }

        [JsonProperty("favoritesCount")]
        public int FavoritesCount { get; set; }

        [JsonProperty("objectType")]
        public string ObjectType { get; set; }

        [JsonProperty("actor")]
        public Actor3 Actor { get; set; }

        [JsonProperty("provider")]
        public Provider3 Provider { get; set; }

        [JsonProperty("twitter_filter_level")]
        public string TwitterFilterLevel { get; set; }

        [JsonProperty("twitter_entities")]
        public TwitterEntities3 TwitterEntities { get; set; }

        [JsonProperty("twitter_lang")]
        public string TwitterLang { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("object")]
        public Object3 Object { get; set; }
    }

}
