// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.TwitterApiClasses
{

    internal class TwitterEntities
    {

        [JsonProperty("urls")]
        public Url[] Urls { get; set; }

        [JsonProperty("hashtags")]
        public Hashtag[] Hashtags { get; set; }

        [JsonProperty("user_mentions")]
        public UserMention[] UserMentions { get; set; }

        [JsonProperty("trends")]
        public object[] Trends { get; set; }

        [JsonProperty("symbols")]
        public object[] Symbols { get; set; }
    }

}
