// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IBMSwissReHackathon.TwitterApiClasses
{

    internal class TwitterApiMainClass
    {

        [JsonProperty("search")]
        public Search Search { get; set; }

        [JsonProperty("tweets")]
        public Tweet[] Tweets { get; set; }

        [JsonProperty("related")]
        public Related Related { get; set; }
    }

}
